---
name: CI - Run Unit Tests - Unstable Compilers
on: [push, pull_request]

jobs:
    test-future:
        name: Run Tests
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                dc: [dmd-master, dmd-beta, ldc-master, ldc-beta]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              run: dub -q test
              continue-on-error: true
